base_url = "https://blog.yaymukund.com"
title = "yaymukund's weblog"
description = "thoughts i'd like to keep around"
default_language = "en"
compile_sass = true
highlight_code = true
highlight_theme = "inspired-github"
build_search_index = true
extra_syntaxes = ["syntaxes"]
generate_feed = true

[extra]
