base_url = "https://blog.yaymukund.com"
build_search_index = true
compile_sass = true
default_language = "en"
description = "thoughts i'd like to keep around"
generate_feed = true
title = "yaymukund's weblog"

[markdown]
extra_syntaxes = ["syntaxes"]
highlight_code = true
highlight_theme = "inspired-github"
smart_punctuation = true

[extra]
