base_url = "https://blog.yaymukund.com"
title = "yaymukund's weblog"
description = "thoughts i'd like to keep around"
default_language = "en"
compile_sass = true
generate_rss = true
highlight_code = true
highlight_theme = "cheerfully-light"
build_search_index = true

[extra]
# Put all your custom variables here
