base_url = "https://blog.yaymukund.com"
title = "yaymukund's weblog"
description = "thoughts i'd like to keep around"
default_language = "en"
compile_sass = true
build_search_index = true
generate_feed = true

[markdown]
highlight_code = true
highlight_theme = "inspired-github"
extra_syntaxes = ["syntaxes"]

[extra]
