#!/usr/bin/env zsh
setopt HIST_SUBST_PATTERN

CONTENT_DIR="content/posts"

vared -p 'post title: ' -c title
slug=${title[1,50]:l:s/% //:gs/ /-/};
file="$CONTENT_DIR/$slug.md";

if [[ -f $file ]]; then
  echo "$file already exists. Oops.";
  exit 1;
fi

cat >$file <<EOL
+++
date = $(date +%Y-%m-%d)
title = "$title"
+++

This is an example of a post.

> It can include a quote. And you're free to *emphasize text*
> within a quote.

-- Mukund

EOL

$EDITOR $file
